fix parsing of owner and repo
OctoMind-dev/jenkins-integration pull request #3
Opened 2023-08-22 14:14 UTC by sinisastanic

2023-08-22 14:50 UTC, sinisastanic commented
@RunOrVeith solving the regex problem 🥰

2023-08-23 00:52 UTC, Germandrummer92 requested changes

2023-08-23 00:52 UTC, Germandrummer92 commented on Jenkinsfile
> +                    matchesOrgAndRepo = null
why this assignment? 🤔

2023-08-23 03:40 UTC, Germandrummer92 commented on Jenkinsfile
> +                    def matchesOrgAndRepo =  ("https://github.com/OctoMind-dev/jenkins-integration.git" =~ ".*(/|:)(.*)/([^\\.]*)(\\.git)?\$")
also: maybe we just send the full git url to the backend and do the splitting/url building there? seems a lot more generic and we don't need to change the jenkinsfile every time?

2023-08-23 22:13 UTC, sinisastanic reviewed
successful run [here](http://35.246.255.232:8080/job/GitHub%20Example%20Pipeline/62/console)

2023-08-23 22:18 UTC, Germandrummer92 approved these changes

2023-08-24 00:36 UTC, merged